# Process compose for starting kubernetes dashboard proxy
version: "0.5"
processes:
  k8s-dashboard:
    command: devbox run k8s:dashboard:proxy
    availability:
      restart: "always"
  kind-lb:
    # https://github.com/kubernetes-sigs/cloud-provider-kind?tab=readme-ov-file#enabling-load-balancer-port-mapping
    command: cloud-provider-kind -enable-lb-port-mapping
    availability:
      restart: "always"
  kind-gateway-alpha:
    # https://github.com/kubernetes-sigs/cloud-provider-kind?tab=readme-ov-file#gateway-api-support-alpha
    # Gateway API is enabled by default and can not be opted-out, users can choose to install the standard or experimental CRDs
    command: cloud-provider-kind
    availability:
      restart: "always"
